// Copyright Mike Desrosiers, All Rights Reserved

#if VIRTUALFLOW_WITH_MVVM && WITH_EDITOR
#include "MVVMVirtualFlowDetails.h"

// VirtualFlowLayouts
#include "VirtualFlowView.h"

// ModelViewViewModelBlueprint
#include <MVVMBlueprintView.h>
#include <MVVMBlueprintViewModelContext.h>
#include <MVVMWidgetBlueprintExtension_View.h>

// UMG
#include <Blueprint/UserWidget.h>

// UMGEditor
#include <WidgetBlueprint.h>
#include <WidgetBlueprintEditor.h>

// UnrealEd
#include <Kismet2/BlueprintEditorUtils.h>

// PropertyEditor
#include <DetailLayoutBuilder.h>
#include <DetailCategoryBuilder.h>
#include <DetailWidgetRow.h>
#include <PropertyCustomizationHelpers.h>
#include <PropertyHandle.h>

// Slate
#include <ScopedTransaction.h>
#include <Framework/MultiBox/MultiBoxBuilder.h>
#include <Widgets/Input/SButton.h>
#include <Widgets/Input/SComboButton.h>
#include <Widgets/Text/STextBlock.h>

TSharedPtr<FVirtualFlowViewDetails> FVirtualFlowViewDetails::MakeInstance()
{
	return MakeShared<FVirtualFlowViewDetails>();
}

void FVirtualFlowViewDetails::CustomizeDetails(
	IDetailLayoutBuilder& InDetailLayout,
	const TArrayView<UWidget*> InWidgets,
	const TSharedRef<FWidgetBlueprintEditor>& InWidgetBlueprintEditor)
{
	if (InWidgets.Num() != 1)
	{
		return;
	}

	UVirtualFlowView* FlowView = Cast<UVirtualFlowView>(InWidgets[0]);
	if (!IsValid(FlowView))
	{
		return;
	}

	Widget = FlowView;
	WidgetBlueprintEditor = InWidgetBlueprintEditor;

	if (GetExtensionViewForSelectedWidgetBlueprint() == nullptr)
	{
		return;
	}

	IDetailCategoryBuilder& MVVMCategory = InDetailLayout.EditCategory("VirtualFlow|Entries");
	const FName NAME_ViewmodelExtension = "ViewmodelExtension";

	// Fetch the entry widget class property handle.
	TArray<TSharedRef<IPropertyHandle>> DefaultProperties;
	MVVMCategory.GetDefaultProperties(DefaultProperties);

	TSharedRef<IPropertyHandle>* EntryClassPtr = DefaultProperties.FindByPredicate(
		[](const TSharedRef<IPropertyHandle>& Property)
		{
			return Property->GetProperty() != nullptr && Property->GetProperty()->GetName() == TEXT("EntryWidgetClass");
		});

	if (EntryClassPtr != nullptr)
	{
		EntryClassHandle = *EntryClassPtr;
		EntryClassHandle->SetOnPropertyValueChanged(
			FSimpleDelegate::CreateSP(this, &FVirtualFlowViewDetails::HandleEntryClassChanged, false));
	}

	bIsExtensionAdded = GetVirtualFlowExtension() != nullptr;
	HandleEntryClassChanged(true);

	// Add/remove extension button.
	MVVMCategory.AddCustomRow(INVTEXT("Viewmodel"))
		.RowTag(NAME_ViewmodelExtension)
		.NameContent()
		[
			SNew(STextBlock)
				.Text(INVTEXT("Viewmodel Extension"))
				.Font(IDetailLayoutBuilder::GetDetailFont())
				.ToolTipText(INVTEXT(
					"Add or remove a Viewmodel Extension. This extension sets a ViewModel on each entry widget generated by this VirtualFlowView."))
		]
		.ValueContent()
		.HAlign(HAlign_Fill)
		[
			SNew(SHorizontalBox)
			+ SHorizontalBox::Slot()
			.AutoWidth()
			[
				SNew(SButton)
					.OnClicked(this, &FVirtualFlowViewDetails::ModifyExtension)
				[
					SNew(SHorizontalBox)
					+ SHorizontalBox::Slot()
					.HAlign(HAlign_Center)
					.VAlign(VAlign_Center)
					.AutoWidth()
					[
						SNew(SImage)
							.Image(this, &FVirtualFlowViewDetails::GetExtensionButtonIcon)
					]
					+ SHorizontalBox::Slot()
					.Padding(FMargin(3.0f, 0.0f, 0.0f, 0.0f))
					.VAlign(VAlign_Center)
					.AutoWidth()
					[
						SNew(STextBlock)
							.TextStyle(FAppStyle::Get(), "SmallButtonText")
							.Text(this, &FVirtualFlowViewDetails::GetExtensionButtonText)
					]
				]
			]
		];

	// Entry ViewModel dropdown (visible only when extension is added).
	MVVMCategory.AddCustomRow(INVTEXT("Entry ViewModel"))
		.RowTag(NAME_ViewmodelExtension)
		.Visibility(TAttribute<EVisibility>::Create(
			TAttribute<EVisibility>::FGetter::CreateSP(this, &FVirtualFlowViewDetails::GetEntryViewModelVisibility)))
		.NameContent()
		[
			SNew(STextBlock)
				.Text(INVTEXT("Entry Viewmodel"))
				.Font(IDetailLayoutBuilder::GetDetailFont())
				.ToolTipText(INVTEXT(
					"Each entry created by this Viewmodel Extension will be bound to this Viewmodel on the entry widget"))
		]
		.ValueContent()
		.HAlign(HAlign_Fill)
		[
			SNew(SHorizontalBox)
			+ SHorizontalBox::Slot()
			.AutoWidth()
			[
				SNew(SComboButton)
					.OnGetMenuContent(this, &FVirtualFlowViewDetails::OnGetViewModelsMenuContent)
					.ButtonContent()
				[
					SNew(STextBlock)
						.Text(this, &FVirtualFlowViewDetails::OnGetSelectedViewModel)
						.ToolTipText(this, &FVirtualFlowViewDetails::OnGetSelectedViewModel)
				]
			]
			+ SHorizontalBox::Slot()
			.AutoWidth()
			[
				PropertyCustomizationHelpers::MakeClearButton(
					FSimpleDelegate::CreateSP(this, &FVirtualFlowViewDetails::ClearEntryViewModel))
			]
		];
}

FReply FVirtualFlowViewDetails::ModifyExtension()
{
	UVirtualFlowView* WidgetPtr = Widget.Get();
	if (!IsValid(WidgetPtr))
	{
		return FReply::Handled();
	}

	if (UMVVMBlueprintViewExtension_VirtualFlow* Ext = GetVirtualFlowExtension(); Ext != nullptr)
	{
		GetExtensionViewForSelectedWidgetBlueprint()->RemoveBlueprintWidgetExtension(Ext, WidgetPtr->GetFName());
		bIsExtensionAdded = false;
	}
	else
	{
		CreateVirtualFlowExtensionIfNotExisting();
		bIsExtensionAdded = true;
	}

	return FReply::Handled();
}

void FVirtualFlowViewDetails::CreateVirtualFlowExtensionIfNotExisting()
{
	UMVVMWidgetBlueprintExtension_View* Extension = GetExtensionViewForSelectedWidgetBlueprint();
	if (!IsValid(Extension))
	{
		return;
	}

	UVirtualFlowView* WidgetPtr = Widget.Get();
	if (!IsValid(WidgetPtr))
	{
		return;
	}

	TArray<UMVVMBlueprintViewExtension*> Extensions = Extension->GetBlueprintExtensionsForWidget(WidgetPtr->GetFName());
	const bool bExists = Extensions.ContainsByPredicate(
		[](UMVVMBlueprintViewExtension* Ext)
		{
			return Cast<UMVVMBlueprintViewExtension_VirtualFlow>(Ext) != nullptr;
		});

	if (bExists)
	{
		return;
	}

	UMVVMBlueprintViewExtension* NewExtension = Extension->CreateBlueprintWidgetExtension(
		UMVVMBlueprintViewExtension_VirtualFlow::StaticClass(), WidgetPtr->GetFName());
	UMVVMBlueprintViewExtension_VirtualFlow* NewFlowExtension =
		CastChecked<UMVVMBlueprintViewExtension_VirtualFlow>(NewExtension);
	NewFlowExtension->WidgetName = WidgetPtr->GetFName();
}

UMVVMBlueprintViewExtension_VirtualFlow* FVirtualFlowViewDetails::GetVirtualFlowExtension() const
{
	UMVVMWidgetBlueprintExtension_View* ViewClass = GetExtensionViewForSelectedWidgetBlueprint();
	if (!IsValid(ViewClass))
	{
		return nullptr;
	}

	UVirtualFlowView* WidgetPtr = Widget.Get();
	if (!IsValid(WidgetPtr))
	{
		return nullptr;
	}

	for (UMVVMBlueprintViewExtension* Extension : ViewClass->GetBlueprintExtensionsForWidget(WidgetPtr->GetFName()))
	{
		if (UMVVMBlueprintViewExtension_VirtualFlow* FlowExt =
			Cast<UMVVMBlueprintViewExtension_VirtualFlow>(Extension))
		{
			return FlowExt;
		}
	}

	return nullptr;
}

UMVVMWidgetBlueprintExtension_View* FVirtualFlowViewDetails::GetExtensionViewForSelectedWidgetBlueprint() const
{
	const TSharedPtr<FWidgetBlueprintEditor> BPEditor = WidgetBlueprintEditor.Pin();
	if (BPEditor == nullptr)
	{
		return nullptr;
	}

	const UWidgetBlueprint* Blueprint = BPEditor->GetWidgetBlueprintObj();
	if (!IsValid(Blueprint))
	{
		return nullptr;
	}

	return UMVVMWidgetBlueprintExtension_View::GetExtension<UMVVMWidgetBlueprintExtension_View>(Blueprint);
}

void FVirtualFlowViewDetails::HandleEntryClassChanged(const bool bIsInit)
{
	void* EntryClassPtr = nullptr;
	TSubclassOf<UUserWidget>* EntryClassValue = nullptr;

	if (EntryClassHandle.IsValid() && EntryClassHandle->IsValidHandle())
	{
		if (EntryClassHandle->GetValueData(EntryClassPtr) == FPropertyAccess::Success)
		{
			EntryClassValue = static_cast<TSubclassOf<UUserWidget>*>(EntryClassPtr);
		}
	}

	const bool bEntryClassChanged = EntryClassValue == nullptr || EntryClass.Get() == nullptr || EntryClass.Get() != *EntryClassValue;
	EntryClass = EntryClassValue != nullptr ? *EntryClassValue : nullptr;

	if (!bEntryClassChanged || !IsValid(EntryClass))
	{
		return;
	}

	if (const UUserWidget* EntryCDO = Cast<UUserWidget>(EntryClass->GetDefaultObject(false)))
	{
		EntryWidgetBlueprint = Cast<UWidgetBlueprint>(EntryCDO->GetClass()->ClassGeneratedBy);
	}

	if (!bIsInit)
	{
		SetEntryViewModel(FGuid(), false);
	}
}

FText FVirtualFlowViewDetails::OnGetSelectedViewModel() const
{
	const UMVVMBlueprintViewExtension_VirtualFlow* FlowExt = GetVirtualFlowExtension();
	if (!IsValid(Widget.Get()) || !IsValid(EntryClass) || !IsValid(FlowExt))
	{
		return INVTEXT("No Viewmodel Extension");
	}

	const UUserWidget* EntryUserWidget = Cast<UUserWidget>(EntryClass->GetDefaultObject(false));
	if (!IsValid(EntryUserWidget))
	{
		return INVTEXT("Invalid Entry Widget");
	}

	const UWidgetBlueprint* EntryBlueprint = Cast<UWidgetBlueprint>(EntryUserWidget->GetClass()->ClassGeneratedBy);
	if (!IsValid(EntryBlueprint))
	{
		return INVTEXT("Invalid Entry Widget Blueprint");
	}

	const UMVVMWidgetBlueprintExtension_View* EntryWidgetExtension =
		UMVVMWidgetBlueprintExtension_View::GetExtension<UMVVMWidgetBlueprintExtension_View>(EntryBlueprint);
	if (!IsValid(EntryWidgetExtension))
	{
		return INVTEXT("Entry Widget has no UMVVMWidgetBlueprintExtension_View");
	}

	const UMVVMBlueprintView* EntryWidgetView = EntryWidgetExtension->GetBlueprintView();
	if (!IsValid(EntryWidgetView))
	{
		return INVTEXT("Entry Widget has no UMVVMBlueprintView");
	}

	const FMVVMBlueprintViewModelContext* ViewModelContext =
		EntryWidgetView->FindViewModel(FlowExt->GetEntryViewModelId());
	if (ViewModelContext == nullptr)
	{
		return INVTEXT("No Viewmodel");
	}

	return FText::FromName(ViewModelContext->GetViewModelName());
}

FText FVirtualFlowViewDetails::GetExtensionButtonText() const
{
	return bIsExtensionAdded
		? INVTEXT("Remove Viewmodel Extension")
		: INVTEXT("Add Viewmodel Extension");
}

const FSlateBrush* FVirtualFlowViewDetails::GetExtensionButtonIcon() const
{
	return bIsExtensionAdded
		? FAppStyle::Get().GetBrush("Icons.X")
		: FAppStyle::Get().GetBrush("Icons.Plus");
}

TSharedRef<SWidget> FVirtualFlowViewDetails::OnGetViewModelsMenuContent()
{
	FMenuBuilder MenuBuilder(true, nullptr);

	if (!IsValid(EntryClass))
	{
		return MenuBuilder.MakeWidget();
	}

	const UWidgetBlueprint* EntryWidgetBlueprintPtr = EntryWidgetBlueprint.Get();
	if (!IsValid(EntryWidgetBlueprintPtr))
	{
		return MenuBuilder.MakeWidget();
	}

	const UMVVMWidgetBlueprintExtension_View* EntryWidgetExtension =
		UMVVMWidgetBlueprintExtension_View::GetExtension<UMVVMWidgetBlueprintExtension_View>(EntryWidgetBlueprintPtr);
	if (!IsValid(EntryWidgetExtension))
	{
		return MenuBuilder.MakeWidget();
	}

	const UMVVMBlueprintView* EntryWidgetView = EntryWidgetExtension->GetBlueprintView();
	if (!IsValid(EntryWidgetView))
	{
		return MenuBuilder.MakeWidget();
	}

	for (const FMVVMBlueprintViewModelContext& EntryViewModel : EntryWidgetView->GetViewModels())
	{
		FUIAction ItemAction(FExecuteAction::CreateSP(
			this, &FVirtualFlowViewDetails::SetEntryViewModel,
			EntryViewModel.GetViewModelId(), true));
		MenuBuilder.AddMenuEntry(
			FText::FromName(EntryViewModel.GetViewModelName()),
			TAttribute<FText>(), FSlateIcon(), ItemAction);
	}

	return MenuBuilder.MakeWidget();
}

void FVirtualFlowViewDetails::ClearEntryViewModel()
{
	SetEntryViewModel(FGuid());
}

void FVirtualFlowViewDetails::SetEntryViewModel(FGuid InEntryViewModelId, bool bMarkModified)
{
	if (!IsValid(Widget.Get()))
	{
		return;
	}

	UMVVMBlueprintViewExtension_VirtualFlow* FlowExt = GetVirtualFlowExtension();
	if (!IsValid(FlowExt))
	{
		return;
	}

	if (FlowExt->GetEntryViewModelId() == InEntryViewModelId)
	{
		return;
	}

	const FScopedTransaction Transaction(INVTEXT("Set Entry ViewModel"));
	FlowExt->Modify();
	FlowExt->EntryViewModelId = InEntryViewModelId;

	if (!bMarkModified)
	{
		return;
	}

	const TSharedPtr<FWidgetBlueprintEditor> BPEditor = WidgetBlueprintEditor.Pin();
	if (BPEditor == nullptr)
	{
		return;
	}

	UWidgetBlueprint* Blueprint = BPEditor->GetWidgetBlueprintObj();
	if (!IsValid(Blueprint))
	{
		return;
	}

	FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(Blueprint);
}

#endif // VIRTUALFLOW_WITH_MVVM && WITH_EDITOR