// Copyright Mike Desrosiers, All Rights Reserved

#pragma once

// Core
#include <CoreMinimal.h>

// CoreUObject
#include <UObject/ObjectKey.h>

#if VIRTUALFLOW_WITH_MVVM
#include <Extensions/MVVMViewClassExtension.h>
#include <Bindings/MVVMCompiledBindingLibrary.h>
#else
// Stubs so UHT can parse the reflected class when the
// ModelViewViewModel plugin is not enabled. The class compiles but
// is never instantiated.
#include <UObject/Object.h>
class UMVVMViewClassExtension : public UObject { public: virtual ~UMVVMViewClassExtension() = default; };
struct FMVVMVCompiledFieldPath {};
class UMVVMView;
#endif

// Internal
#include "MVVMViewVirtualFlowClassExtension.generated.h"

class UUserWidget;
class UVirtualFlowView;

/**
 * Runtime MVVM extension that automatically sets the entry ViewModel on pooled
 * entry widgets generated by UVirtualFlowView.
 *
 * Created at WBP compile time by UMVVMBlueprintViewExtension_VirtualFlow.
 * At construct it binds to UVirtualFlowView::OnItemWidgetGenerated; when a
 * new entry widget is realized it locates the entry's UMVVMView and calls
 * SetViewModel with the UObject* item that was bound.
 *
 * When the ModelViewViewModel plugin is not enabled this class compiles as an
 * inert UObject stub that is never instantiated.
 */
UCLASS()
class VIRTUALFLOWLAYOUTSMVVM_API UMVVMViewVirtualFlowClassExtension : public UMVVMViewClassExtension
{
	GENERATED_BODY()

public:
#if VIRTUALFLOW_WITH_MVVM
	void Initialize(FName InWidgetName, FName InEntryViewModelName, FMVVMVCompiledFieldPath InWidgetPath);

	//~ Begin UMVVMViewClassExtension
	void OnSourcesInitialized(UUserWidget* UserWidget, UMVVMView* View, UMVVMViewExtension* Extension) override;
	void OnSourcesUninitialized(UUserWidget* UserWidget, UMVVMView* View, UMVVMViewExtension* Extension) override;
	//~ End UMVVMViewClassExtension
#endif

private:
	UFUNCTION()
	void HandleItemWidgetGenerated(UObject* Item, UUserWidget* ItemWidget);

	UPROPERTY()
	FName WidgetName;

	UPROPERTY()
	FName EntryViewModelName;

	UPROPERTY()
	FMVVMVCompiledFieldPath WidgetPath;

	/** Caches the resolved UVirtualFlowView per owning UMVVMView so we can unbind cleanly. */
	TMap<FObjectKey, TWeakObjectPtr<UVirtualFlowView>> CachedFlowViewWidgets;
};